namespace: pipelineiq
replicaCount: 1

image:
  repository: pipelineiqproda81487xyepacr.azurecr.io/final_capstone-notification-service
  tag: e8455455790a

service:
  enabled: false

envFrom:
  configMapName: pipelineiq-config
  secretName: pipelineiq-kv-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 50m
    memory: 48Mi
  limits:
    cpu: 250m
    memory: 256Mi
