namespace: pipelineiq
replicaCount: 1

image:
  repository: nimeshsv814/final_capstone-webhook-service
  tag: v1.0.4

containerPort: 8087

service:
  enabled: true
  port: 8087
  targetPort: 8087

envFrom:
  configMapName: pipelineiq-config
  secretName: pipelineiq-kv-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 50m
    memory: 48Mi
  limits:
    cpu: 250m
    memory: 256Mi
