name: gemini-ai-service
namespace: pipelineiq-prod
replicaCount: 2

image:
  repository: nimeshsv814/final_capstone-gemini-ai-service
  tag: v1.0.5
  pullPolicy: IfNotPresent

containerPort: 8085

service:
  port: 8085
  targetPort: 8085

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30

probes:
  enabled: false
  readinessPath: /health
  livenessPath: /health

envFrom:
  enabled: true
  configMapName: pipelineiq-config
  secretName: pipelineiq-kv-secrets

keyvaultMount:
  enabled: true
  secretProviderClass: pipelineiq-keyvault-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 384Mi
