namespace: pipelineiq-prod

keyVault:
  secretProviderClassName: pipelineiq-keyvault-secrets
  name: pipelineiqproda814kv
  tenantId: a9c0d434-d5c8-4c38-aab2-f3041871ebf8
  userAssignedIdentityID: 3a5ce30d-96a6-46c4-8822-53cf72418617
  objects:
    - objectName: node-env
    - objectName: frontend-url
    - objectName: public-api-base-url
    - objectName: public-auth-base-url
    - objectName: auth-service-url
    - objectName: dashboard-api-url
    - objectName: github-service-url
    - objectName: pipeline-runner-url
    - objectName: analyzer-service-url
    - objectName: gemini-service-url
    - objectName: notification-service-url
    - objectName: github-callback-url
    - objectName: auth-provider
    - objectName: entra-tenant-id
    - objectName: entra-client-id
    - objectName: entra-callback-url
    - objectName: session-ttl
    - objectName: ai-provider
    - objectName: ai-fallback-enabled
    - objectName: ai-fallback-provider
    - objectName: gemini-model
    - objectName: azure-openai-endpoint
    - objectName: azure-openai-deployment
    - objectName: azure-openai-api-version
    - objectName: queue-provider
    - objectName: rabbitmq-url
    - objectName: servicebus-namespace
    - objectName: smtp-port
    - objectName: github-client-id
    - objectName: github-client-secret
    - objectName: github-webhook-secret
    - objectName: jwt-secret
    - objectName: token-encryption-key
    - objectName: database-url
    - objectName: gemini-api-key
    - objectName: azure-openai-api-key
    - objectName: entra-client-secret
    - objectName: servicebus-connection-string
    - objectName: smtp-host
    - objectName: smtp-user
    - objectName: smtp-password
    - objectName: smtp-from
