name: pipeline-runner-service
namespace: pipelineiq-prod
replicaCount: 2

image:
  repository: nimeshsv814/final_capstone-pipeline-runner-service
  tag: v1.0.4
  pullPolicy: IfNotPresent

containerPort: 8083

service:
  port: 8083
  targetPort: 8083

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30

probes:
  enabled: false
  readinessPath: /health
  livenessPath: /health

keyvaultMount:
  enabled: true
  secretProviderClass: pipelineiq-keyvault-secrets

keyVaultEnv:
  enabled: true

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 50m
    memory: 48Mi
  limits:
    cpu: 250m
    memory: 256Mi
