namespace: pipelineiq
replicaCount: 1

image:
  repository: acrchandana.azurecr.io/final_capstone-auth-service
  tag: v1.1.0

containerPort: 8081

service:
  enabled: true
  port: 8081
  targetPort: 8081

envFrom:
  configMapName: pipelineiq-config
  secretName: pipelineiq-kv-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 50m
    memory: 48Mi
  limits:
    cpu: 250m
    memory: 256Mi
