namespace: pipelineiq
replicaCount: 1

image:
  repository: pipelineiqproda81487xyepacr.azurecr.io/final_capstone-gemini-ai-service
  tag: d70d8e317e88

service:
  enabled: false

envFrom:
  configMapName: pipelineiq-config
  secretName: pipelineiq-kv-secrets

keyvaultMount:
  enabled: true
  secretProviderClass: pipelineiq-keyvault-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 384Mi
