name: auth-service
namespace: pipelineiq-prod
replicaCount: 2

image:
  repository: pipelineiqproda81487xyepacr.azurecr.io/final_capstone-auth-service
  tag: v1.1.0
  pullPolicy: IfNotPresent

containerPort: 8081

service:
  port: 8081
  targetPort: 8081

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30

probes:
  enabled: true
  readinessPath: /health
  livenessPath: /health

keyvaultMount:
  enabled: true
  secretProviderClass: pipelineiq-keyvault-secrets

keyVaultEnv:
  enabled: true

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 50m
    memory: 48Mi
  limits:
    cpu: 250m
    memory: 256Mi
