apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.ports.amqp }}
      targetPort: {{ .Values.ports.amqp }}
    - name: management
      port: {{ .Values.ports.management }}
      targetPort: {{ .Values.ports.management }}
