name: workflow-analyzer-service
namespace: pipelineiq-prod
replicaCount: 2

image:
  repository: pipelineiqproda81487xyepacr.azurecr.io/final_capstone-workflow-analyzer-service
  tag: v1.1.0
  pullPolicy: IfNotPresent

containerPort: 8084

service:
  port: 8084
  targetPort: 8084

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30

probes:
  enabled: false
  readinessPath: /health
  livenessPath: /health

keyvaultMount:
  enabled: true
  secretProviderClass: pipelineiq-keyvault-secrets

keyVaultEnv:
  enabled: true

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 384Mi
