namespace: pipelineiq
replicaCount: 1

image:
  repository: acrchandana.azurecr.io/final_capstone-workflow-analyzer-service
  tag: v1.1.0

service:
  enabled: false

envFrom:
  configMapName: pipelineiq-config
  secretName: pipelineiq-kv-secrets

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 384Mi
